security:
    access_decision_manager:
        strategy: unanimous
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        users_in_memory: { memory: null }
        in_database:
            entity: 
                class: App\Entity\User
                #property: email
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: false
            lazy: true
            provider: in_database
            form_login:
                login_path: security_login
                check_path: security_login
                default_target_path: employee
            logout:
                path: security_logout
                target: security_login
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 36000 # 10H in seconds
                path:     /
                # by default, the feature is enabled by checking a
                # checkbox in the login form (see below), uncomment the
                # following line to always enable it.
                # always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_EDITOR: ROLE_USER   
        ROLE_MODO: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_USER]
