<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => 'fa3258c0f8af93c758717ff36fb654eb',
  'DATABASE_URL' => 'mysql://root:root@127.0.0.1:3306/planning-e4',
);
